version: "3.9"
services:
  backend:
    build: ./backend
    container_name: omio-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    container_name: omio-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend