apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: busly
data:
  NODE_ENV: production
  MONGO_URI: mongodb://mongo:27017/busly
  FRONTEND_URL: http://busly.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: busly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mrkskq44/busly-backend:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: backend-config
